[package]
name = "day6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fst"
path = "src/fst.rs"

[[bin]]
name = "snd"
path = "src/snd.rs"

[dependencies]
itertools = "0.12.0"
